name = "fiqri-dev"
compatibility_date = "2026-09-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fiqri-dev"
database_id = "d4f30441-314d-4b42-b940-54fb45e25b92"
migrations_dir = "../../migrations"
